### ISSUE TITLE
OpenParrotLoader.exe flagged as Trojan:Win32/Sabsik.TE.A!ml

### ISSUE THREAD

**Issue by HQuest** [teknogods/OpenParrot#156]
After downloading the OpenParrotWin32.zip from the releases section of this Github repo, Windows Security is flagging the OpenParrotLoader.exe as malware. Other vendors are flagging it as well - see https://www.virustotal.com/gui/file/b9d2bb4de2fd06781bba9d231f110ae3728f5f3d8732dcd044381d5df0161722/detection

**Comment by nzgamer41** [comment]
Yeah this happens, it's a false positive, it comes up because openparrotloader injects our DLL (openparrot/teknoparrot(64).dll) into the games rather then modifying them and releasing hacked exes per game. This injecting of a dll into an application is similar to how some malware works, however with teknoparrot it is a false positive. We've tried appealing it with antivirus vendors eg Microsoft Defender however that only covers that specific release and due to our continuous integration it's impractical to send the files to vendors every time a commit is made.
