### ISSUE TITLE
KOF Sky Stage Wrong Orientation

### ISSUE THREAD

**Issue by EllimistArcade** [teknogods/OpenParrot#249]
KOF Sky Stage launches rotated 90 degrees clockwise with an NVIDIA graphics card. There does not seem to be any way to resolve this problem. 

https://imgur.com/a/oQfjXhe

**Comment by EmiMidnight** [comment]
Windowed mode should rotate the image properly now with the next Openparrot update in a few minutes.

**Comment by EllimistArcade** [comment]
I have confirmed that this fixed the matter in Windowed mode. Thank you!

This issue is still present in non-Windowed mode (Windowed mode Unchecked)

**Comment by EllimistArcade** [comment]
Ah ok, can do that. Was just using a standard PC monitor on a Windows machine and it started rotated. 

I can use monitor configuration to rotate screen, but not sure if it should start correctly oriented and just wanted to make sure it was noted.

**Comment by EmiMidnight** [comment]
I've taken a closer look at the game and it seems they expect the physical screen to be rotated, so they just render it like this for it to work. No windows display rotation done. 

So far attempts to fix it in fullscreen mode have failed because most monitors (including mine) do not support vertical resolutions in a landscape configuration. :(

**Comment by EllimistArcade** [comment]
That makes perfect sense. Thank you Emi! I will get the compatibility game page updated with this information so its visible to anyone else that comes looking. And with Windowed mode oriented correctly I think we can close this issue out.
